### ISSUE TITLE
Http.Headers request: adding X-CSRFToken headers to requests

### ISSUE THREAD

**Issue by bitterjug** [elm-lang/http#13]
Django and Rails like this header to be set on requests to apis. It'd be very convenient to have an easy way to add  this header to, e.g. post requests without building custom requests.

**Comment by evancz** [comment]
I don't think it makes sense to have that in the core API with the information I have now. Outline the API you want and then let's review again. Maybe it makes sense as a separate package. Maybe here. Need more info.

**Comment by bitterjug** [comment]
Thanks @evancz 

If I understand correctly, `Request a` is opaque. So having created a post request with `post` I can no longer pull out the headers list to add a header to. So I have to build my post request with `request`.  Well, fine. But I think it'd be nice to be able to say something like:

``` elm
      Http.post "https://example.com/books" Http.emptyBody (list string)
        |> withHeaders [  header "X-CSRFToken" token ]
```

Which appends my header list to those already in the request.

**Comment by fbonetti** [comment]
@bitterjug I recommend checking out the [elm-http-builder](http://package.elm-lang.org/packages/lukewestby/elm-http-builder/latest) library. It allows requests to be pipeline/modified and has functions like [`withHeader`](http://package.elm-lang.org/packages/lukewestby/elm-http-builder/5.0.0/HttpBuilder#withHeader) and [`withHeaders`](http://package.elm-lang.org/packages/lukewestby/elm-http-builder/5.0.0/HttpBuilder#withHeaders).
