### ISSUE TITLE
Expose mapExpect

### ISSUE THREAD

**Issue by toastal** [elm-lang/http#16]
Upgrading to 0.18 I found some code a coworker wrote reusing one request and `Task.map`ping the response to make another useful HTTP-related function. I see that you have `Http.Internal.Response.map` and `mapExpect` in the Native code; black-boxing `Request` is fine, but being able to operate inside it when necessary would be nice. Or perhaps `expectAndThen` or `mapAfter`?

**Comment by evancz** [comment]
Can you show the code that inspired this request?

**Comment by evancz** [comment]
I do not want to expose more internal details without a concrete use case.
