### ISSUE TITLE
Http.request's weird behavior 

### ISSUE THREAD

**Issue by jackalcooper** [elm-lang/http#20]
```elm
Http.request
            { method = verb
            , headers =
                [ (header "Accept" "application/json")
                , (header "Content-Type" "application/json")
                ]
            , url = Config.endpointUrl
            , body = Http.jsonBody <| params
            , expect = expectJson decoder
            , timeout = Nothing
            , withCredentials = False
            }
```
When I have "application/json" for both "Accept" and "Content-Type" headers. The request I got has two "application/json" for Content-Type header

**Comment by jackalcooper** [comment]
Close for now cause I can't reproduce it in Elm try

**Comment by romariolopezc** [comment]
I have the same issue.
`Content-Type:application/json, application/json`

**Comment by zwilias** [comment]
@romariolopezc @jackalcooper When using `Http.jsonBody`, the `Content-Type: application/json` header is automatically set. Hence, manually setting it, results in the header being set twice.

**Comment by jackalcooper** [comment]
@zwilias I see, thank you
