### ISSUE TITLE
Expose Internal.RawRequest (and maybe a 'defaultRequestFields')

### ISSUE THREAD

**Issue by mltsy** [elm-lang/http#23]
When trying to create a new request from scratch, it sure would be nice to have a type I can use to define a function called `defaultRequestFields` so that I don't have to enumerate all the fields of the request in every function that builds a different kind of request.  Turns out that type is `Http.Internal.RawRequest`! :smiley: 

Also, if we expose that type, why not also expose a method called `defaultRequestFields` so that if I want to create a new request all I have to do is:

``` elm
buildRequestWithCredentials : String -> Request String
buildRequestWithCredentials url =
  request
    { defaultRequestFields
    | withCredentials = True,
    , url = url
    }
```

Or if I have my own default Request fields, I can say:

``` elm
defaultRequestFields : RawRequest
defaultRequestFields =
  let
    defaultFields = Http.defaultRequestFields
  in
    { defaultFields
    | withCredentials = True
    , expect = Http.expectJson decoder
    }
```

(And then replace the URL as needed)

**Comment by spinus** [comment]
I'm also having same pain. Would be great to "modify" request after it's created.

**Comment by toastal** [comment]
I just needed this too--in the same way. I think `map` on request would suffice.

**Comment by toastal** [comment]
To get around this, I'm creating my own `Request`-like type alias and my own `send` that accepts this request. It's a very smelly solution, but without `(a -> b) -> Request a -> Request b`, to update what is essentially a tagged record, I don't see a better solution. If it's not anything that's going to be fixed, someone could make an alternative HTTP library or Request library that wraps this library with the ability to actually manipulate the request record. I'd do it, but I'm gonna be leaving Elm for the foreseeable future.

**Comment by evancz** [comment]
I tried to address why this information is private in #1

**Comment by mltsy** [comment]
My issue was mostly just what I said in my original post.  I have a function called `buildRequestWithCredentials` where I basically just wanted the same output as `get` but with `withCredentials=true`.  So finding and inserting all the default values for all the fields except that one was an unexpectedly verbose way to have to do that.  Not a huge deal - just seems like it should be more concise.

**Comment by toastal** [comment]
I had to give up entirely do it via ports. When I received a 403, a token had expired. I needed to then do a new token request to a different API endpoint. When that returned with a new token I needed to modify the the original request to include the new token and retry the send.
