### ISSUE TITLE
encodeURIComponent can throw errors

### ISSUE THREAD

**Issue by jinjor** [elm-lang/http#25]
I ran into a runtime error when I tried to include `🍝�👳` in URL. It was my mistake but I think it should be `BadUrl` error in this case.

```
Uncaught URIError: URI malformed
    at encodeURIComponent (<anonymous>)
    at encodeUri (index.js:10938)
    at Function.func (index.js:22317)
    at A2 (index.js:92)
    at search (index.js:38236)
    at index.js:13466
    at index.js:16
    at A2 (index.js:93)
    at Function.func (index.js:13533)
    at A4 (index.js:104)
```

https://github.com/elm-lang/http/blob/99c00a2dac21dda1d4954515c79e6f28e431573f/src/Native/Http.js#L8

* OS: Windows 7
* Browser: Chrome 56
* Elm: 0.18.0
* elm-lang/http: 1.0.0

**Comment by evancz** [comment]
I cannot reproduce the error with this information. Do you have the exact URL you used?

**Comment by jinjor** [comment]
Oh, now I cannot reproduce it either (on Mac, Chrome 60). I'll come back with SSCCE if I find it again!

**Comment by evancz** [comment]
Okay, I'll close in the meantime. Put it over at https://github.com/elm-lang/url if you find it again!

I *suspect* it may fail if you have an invalid surrogate pair, but I think I can rule that out in the parser by making those invalid string literals.
