### ISSUE TITLE
Method to add header to existing request

### ISSUE THREAD

**Issue by abingham** [elm-lang/http#27]
I can't find a way to add a header to an existing request. I've got a situation where I need to add a JWT header to all of my requests for logged in users. The straightforward solution seems to be creating a version of `send` that adds the new header to each request and then calls `Http.send`. However, it doesn't seem possible to add headers to existing requests.

Am I missing something in the current API? Is what I'm asking for a bad idea?

**Comment by michie1** [comment]
http://package.elm-lang.org/packages/elm-lang/http/1.0.0/Http#request

**Comment by evancz** [comment]
You can define a custom kind of request in terms of `request` that adds whatever you need. You can then use those custom functions instead of the normal `get` and `post`. This way people writing the code actually know what requests they are making, rather than having to do an audit of the entire system to see if people were adding and removing and changing headers somewhere else.

**Comment by abingham** [comment]
> This way people writing the code actually know what requests they are making, rather than having to do an audit of the entire system to see if people were adding and removing and changing headers somewhere else.

They'd still have to audit the system to make sure everyone is using the correct version of `get` or `post`, though. Your point is true but feels sorta zero-sum.

A customization point between request creation and `send` (or on `send` itself) feels like a natural and useful thing. It certainly feels better (to me, at least) than requiring the creation of new request builders for every HTTP method I want to support, methods which are almost entirely duplicates of existing functions.

**Comment by PEshwar** [comment]
Hi @evancz -> Is there a sample code snippet available that illustrates how to do add headers to say, Http.get request?

**Comment by abingham** [comment]
@PEshwar I'm pretty sure you can't. You need to re-implement it entirely to add your custom header. The return value of `get` is opaque and not subject to client manipulation.

**Comment by PEshwar** [comment]
Thanks Austin. I took the route of implementing custom request to add headers.

**Comment by pietro909** [comment]
I think there is a specific use case for this: is common for a web app to have a set of mandatory headers (ie: tokens, device information, version number, ...) when dealing with an API.

In Angular, for instance, this is done using [interceptors (https://angular.io/api/common/http/HttpInterceptor).

While I'm not a fan of the _interceptors_ pattern, I have to admit that reimplementing each time all the request builders for each method feels awkward. Moreover, there's no way to enforce their usage but code reviews and self-discipline.
