### ISSUE TITLE
How to handle Server-side redirects?

### ISSUE THREAD

**Issue by skinnyjames** [elm-lang/http#29]
When a user is unauthenticated, I'd like to use the server to redirect to a login page.
On remote http requests, the login page is returned in the response instead.
Is there a way to handle this?

Thanks!

**Comment by evancz** [comment]
Can you ask around on [the Elm slack](http://elmlang.herokuapp.com/) and see what folks say? If it seems to be an issue with the library, please open a new issue that outlines the technical requirements more clearly.
