### ISSUE TITLE
Native.Http.mapExpect is not defined

### ISSUE THREAD

**Issue by jweir** [elm-lang/http#3]
I was trying to create a Progress example, but hit this error. 

`Uncaught TypeError: _elm_lang$http$Native_Http.mapExpect is not a function`

It appears that Native does not define `mapExpect` used by Internal:
https://github.com/elm-lang/http/blob/master/src/Http/Internal.elm#L45

**Comment by evancz** [comment]
I think it'll be fixed, but I'm not 100% certain. Delete your `elm-stuff/` and try again. If it's still bad, please give an http://sscce.org so I can recreate it myself.
