### ISSUE TITLE
Http.RateLimit is missing

### ISSUE THREAD

**Issue by danstn** [elm-lang/http#8]
Should this package actually export `Http.RateLimit` as per [rate-limit.md](https://github.com/elm-lang/http/blob/master/rate-limit.md)? :)

...or was it just a sketch of what it might look like in future?

**Comment by evancz** [comment]
Just a sketch for now. There are three different approaches I am exploring and there's not a clear winner right now. Of the packages that do it in the meantime, I think https://github.com/jinjor/elm-debounce is very well done.
